### ISSUE TITLE
Prelogin failed with message: Valid client certificate is required

### ISSUE THREAD

**Issue by Anduin2017** [liuxintong/xconnect#3]
Prelogin failed with message:

```xml
<prelogin-response>
<status>Error</status>
<ccusername></ccusername>
<autosubmit></autosubmit>
<msg>Valid client certificate is required</msg>
<newmsg>Required client certificate not found. Please contact your IT administrator.</newmsg>
<license>yes</license>
<authentication-message></authentication-message>
<username-label></username-label>
<password-label></password-label>
<panos-version>1</panos-version><region>CN</region>
</prelogin-response>
```

Seems that you did not submit the correct certificate while calling the sign in API.

![Screenshot from 2020-11-12 23-53-17](https://user-images.githubusercontent.com/19531547/98963146-4b84dd80-2542-11eb-8997-d99cf497b024.png)

**Comment by liuxintong** [comment]
Your endpoint was wrong, and this one has enforced certificate authentication. Will share more available endpoints with you offline.
